---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: psdb
  POSTGRES_USER: psuser
  POSTGRES_PASSWORD: pspassword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:14'
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    skupper.io/proxy: "tcp" # <1>
  labels:
    app: postgres
spec:
  type: "ClusterIP"
  ports:
    - port: 5432
  selector:
    app: postgres
